spring:
  application:
    name:cohort-36-shop
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

  key:
    access: u6IWyTFLVdjo0lv58z/jdQlBfoL970Ty8neqaM+D6/g=
    refresh: qzc/VaTdtsoo8cnZlogRiYIr7CqTtJOufkj60hELFQQ=
message:
  hello:Hello from Digital Ocean!
